AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BrainfuckFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["x86_64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: .
      Events:
        Brainfuck:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /brainfuck
            Method: post

Outputs:
  RestApi:
    Description: "API Gateway endpoint URL for Prod stage for Brainfuck function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/brainfuck/"
  BrainfuckFunction:
    Description: "Brainfuck World Lambda Function ARN"
    Value: !GetAtt BrainfuckFunction.Arn
  BrainfuckFunctionIamRole:
    Description: "Implicit IAM Role created for Brainfuck World function"
    Value: !GetAtt BrainfuckFunctionRole.Arn